name: Deps for WordPress

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
    - id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.FHD_DEPS_GITHUB_APP_ID }}
        private_key: ${{ secrets.FHD_DEPS_GITHUB_APP_KEY }}
    - uses: actions/checkout@v2
      with:
        token: ${{ steps.generate_token.outputs.token }}
    - uses: actions/setup-python@v2
    - run: curl https://deps.app/install.sh | bash -s -- -b $HOME/bin
    - run: $HOME/bin/deps ci
      env:
        DEPS_TOKEN: ${{ secrets.DEPS_TOKEN }}
        DEPS_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
